version: 0.2

env:
  repository_name: meetupdemo

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  
  pre_build:
    commands:
      - aws ecr create-repository --repository-name $repository_name --image-tag-mutability IMMUTABLE
  build:
    commands:
      - terraform --version
      - terraform init -input=false
      - terraform validate
      - terraform apply --auto-approve